language: node_js
node_js: 12.18.2
cache: npm

install:
  - npm ci

script:
  - npm test

deploy:
  provider: lambda
  function_name: "lambda-test"
  region: "us-east-1"
  role: "arn:aws:iam::0123456789012:role/lambda_basic_execution"
  runtime: "nodejs12.x"
  handler_name: "handler"
